<h2>Editar Tareas</h2>

<form action = "<?php echo APP_URL.'tareas/edit';?>" method = "POST">

<input type = "hidden" name="id" value="<?php echo $this->tarea['id']; ?>">

	<P>Nombre <input type="text" name = "nombre" value="<?php echo $this->tarea['nombre']; ?>"></P>
	<P>Fecha<input type="text" name = "fecha" value="<?php echo $this->tarea['fecha']; ?>"></P>
	<P>Prioridad<input type="text" name = "prioridad" value="<?php echo $this->tarea['prioridad']; ?>"></P>
	<P>Status<input type="text" name = "status" value="<?php echo $this->tarea['status']; ?>"></P>
	<P><input type="submit"></P>
 
 </form>